# Compose current coverage from a freshly checked rolling sweep and three actual
# native repair recipes. Counts remain separate by strategy; never relabel the
# rolling failures as rolling successes or isolated spells as a continuous stage.
include("${CMAKE_CURRENT_LIST_DIR}/headless_report_checks.cmake")
foreach(required IN ITEMS EXECUTABLE COMPARE_EXECUTABLE DAT SWEEP_DIR SPELL202_DIR SPELL203_DIR EXTRA_DIR WORK OUTPUT)
  if(NOT ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
if(EXISTS "${WORK}")
  message(FATAL_ERROR "Completion verification needs a fresh WORK directory")
endif()
file(MAKE_DIRECTORY "${WORK}")
file(SHA256 "${EXECUTABLE}" native_hash)
file(SHA256 "${COMPARE_EXECUTABLE}" comparison_hash)
file(SHA256 "${DAT}" dat_hash)
file(READ "${SWEEP_DIR}/summary.json" sweep)
field("${sweep}" native_executable_sha256 sweep_native)
field("${sweep}" dat_sha256 sweep_dat)
field("${sweep}" spell_clears spell_clears)
field("${sweep}" stage_clears stage_clears)
field("${sweep}" spell_cases spell_cases)
field("${sweep}" stage_cases stage_cases)
if(NOT sweep_native STREQUAL "\"${native_hash}\"" OR NOT sweep_dat STREQUAL "\"${dat_hash}\"" OR
   NOT spell_clears EQUAL 54 OR NOT stage_clears EQUAL 8 OR
   NOT spell_cases EQUAL 56 OR NOT stage_cases EQUAL 9)
  message(FATAL_ERROR "Rolling sweep is outside the reviewed 54/56 + 8/9 scope")
endif()
# Totals alone would not prove that these repairs cover the actual gaps. Bind
# their identities to the rolling failures instead of adding duplicate successes.
foreach(name IN ITEMS spell-202 spell-203 stage-extra)
  file(READ "${SWEEP_DIR}/${name}.json" baseline)
  field("${baseline}" outcome outcome)
  field("${baseline}" stage stage)
  field("${baseline}" requested_spell_id spell)
  set(expected -1)
  if(name MATCHES "^spell-([0-9]+)$")
    set(expected "${CMAKE_MATCH_1}")
  endif()
  if(NOT outcome STREQUAL "\"collision\"" OR NOT stage STREQUAL "\"extra\"" OR
     NOT spell EQUAL expected)
    message(FATAL_ERROR "${name}: repaired coverage does not match a rolling gap")
  endif()
endforeach()
set(repairs "")
function(verify_repair label directory spell difficulty expected_frames)
  file(SHA256 "${directory}/summary.json" source_hash)
  file(READ "${directory}/summary.json" search)
  field("${search}" outcome outcome)
  field("${search}" child_executable_sha256 child_hash)
  field("${search}" selected_case selected)
  string(REPLACE "\"" "" selected "${selected}")
  if(NOT outcome STREQUAL "\"complete\"" OR NOT child_hash STREQUAL "\"${native_hash}\"" OR
     NOT selected MATCHES "^[A-Za-z0-9_-]+$")
    message(FATAL_ERROR "${label}: unverified repair or native identity mismatch")
  endif()
  file(READ "${directory}/${selected}.json" original)
  # This producer's search summary has exactly one nested execution report;
  # compare its semantic fields/collision with the standalone selected report
  # before treating either the route or its recorded costs as current evidence.
  agree("${search}" "${original}")
  field("${original}" frames frames)
  field("${original}" frame_budget cap)
  field("${original}" prefix_frame prefix)
  field("${original}" requested_spell_id actual_spell)
  field("${original}" difficulty actual_difficulty)
  field("${original}" seed actual_seed)
  if(NOT frames EQUAL expected_frames OR NOT actual_spell EQUAL spell OR
     NOT actual_difficulty EQUAL difficulty OR NOT actual_seed EQUAL 0)
    message(FATAL_ERROR "${label}: wrong repaired scene")
  endif()
  set(args --dat "${DAT}" --stage extra --difficulty ${difficulty} --seed 0
    --frames ${cap} --prefix-frame ${prefix} --replay "${directory}/${selected}.actions")
  if(NOT spell LESS 0)
    list(APPEND args --spell-id ${spell})
  endif()
  foreach(mode IN ITEMS fresh comparison)
    set(exe "${EXECUTABLE}")
    if(mode STREQUAL "comparison")
      set(exe "${COMPARE_EXECUTABLE}")
    endif()
    execute_process(COMMAND "${exe}" ${args} --output "${WORK}/${label}-${mode}.json"
      RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "${label}: ${mode} replay failed: ${error}")
    endif()
    file(READ "${WORK}/${label}-${mode}.json" replay)
    agree("${original}" "${replay}")
    set(${mode} "${replay}")
  endforeach()
  file(SHA256 "${directory}/summary.json" final_hash)
  if(NOT source_hash STREQUAL final_hash)
    message(FATAL_ERROR "${label}: source search changed during verification")
  endif()
  file(SHA256 "${directory}/${selected}.actions" actions_hash)
  list(APPEND repairs "{\"case\":\"${label}\",\"search_sha256\":\"${source_hash}\",\"actions_sha256\":\"${actions_hash}\",\"search\":${search},\"fresh_replay\":${fresh},\"comparison_replay\":${comparison}}")
  set(repairs "${repairs}" PARENT_SCOPE)
  message(STATUS "${label}: complete${frames}; fresh O3/O0 agrees")
endfunction()
# This completion used exactly one prior episode. Preserve its full cost and
# selected failure alongside the resumed search, including the hash-bound inputs.
file(READ "${EXTRA_DIR}/prior/summary.json" prior)
file(SHA256 "${EXTRA_DIR}/prior/manifest.tsv" prior_manifest_hash)
file(SHA256 "${EXTRA_DIR}/prior/summary.json" prior_summary_hash)
file(STRINGS "${EXTRA_DIR}/prior/manifest.tsv" summary_entries REGEX "^summary[.]json\t")
list(LENGTH summary_entries summary_count)
if(NOT summary_count EQUAL 1)
  message(FATAL_ERROR "Extra lineage has no unique prior summary binding")
endif()
string(REPLACE "\t" ";" summary_entry "${summary_entries}")
list(LENGTH summary_entry summary_fields)
if(NOT summary_fields EQUAL 2)
  message(FATAL_ERROR "Malformed prior summary manifest entry")
endif()
list(GET summary_entry 1 recorded_summary_hash)
if(NOT recorded_summary_hash STREQUAL prior_summary_hash)
  message(FATAL_ERROR "Prior Extra summary differs from its sealed manifest")
endif()
file(READ "${EXTRA_DIR}/summary.json" extra)
field("${extra}" prior_manifest_sha256 recorded_manifest)
if(NOT recorded_manifest STREQUAL "\"${prior_manifest_hash}\"")
  message(FATAL_ERROR "Extra lineage manifest changed")
endif()
verify_repair(id202 "${SPELL202_DIR}" 202 4 4712)
verify_repair(id203 "${SPELL203_DIR}" 203 4 5492)
verify_repair(extra "${EXTRA_DIR}" -1 0 92339)
file(SHA256 "${EXECUTABLE}" final_native)
file(SHA256 "${COMPARE_EXECUTABLE}" final_comparison)
if(NOT native_hash STREQUAL final_native OR NOT comparison_hash STREQUAL final_comparison)
  message(FATAL_ERROR "Replay executable changed during completion verification")
endif()
string(JOIN ",\n" repairs_json ${repairs})
file(WRITE "${OUTPUT}"
  "{\"producer\":\"tests/headless_completion.cmake\",\"seed\":0,\"complete_checkpoint_recipes\":56,\"complete_continuous_stage_recipes\":9,\"native_executable_sha256\":\"${native_hash}\",\"comparison_executable_sha256\":\"${comparison_hash}\",\"dat_sha256\":\"${dat_hash}\",\"rolling_sweep\":${sweep},\"extra_prior_search\":${prior},\"extra_prior_manifest_sha256\":\"${prior_manifest_hash}\",\"repairs\":[${repairs_json}]}\n")
