# Optional full-portfolio/stage experiment, deliberately outside the small CTest
# default. Every case runs native state continuously and then replays from scratch.
# The fixed 42 Easy + 14 Extra practice IDs mirror g_SpellcardNumbersEasy/Extra;
# IDs44..46 are other difficulties despite their unconditional ECL start records.
include("${CMAKE_CURRENT_LIST_DIR}/headless_report_checks.cmake")
if(NOT DEFINED SEED)
  set(SEED 0)
endif()
string(LENGTH "${SEED}" seed_length)
if(NOT SEED MATCHES "^[0-9]+$" OR seed_length GREATER 5 OR SEED GREATER 65535)
  message(FATAL_ERROR "SEED must be an unsigned 16-bit integer")
endif()
if(NOT EXECUTABLE OR NOT DAT OR NOT WORK OR EXISTS "${WORK}")
  message(FATAL_ERROR "Supply EXECUTABLE, DAT and a fresh WORK directory")
endif()
file(MAKE_DIRECTORY "${WORK}")
file(SHA256 "${EXECUTABLE}" native_hash)
file(SHA256 "${DAT}" dat_hash)
set(records "")
set(spell_clears 0)
set(stage_clears 0)
set(total_updates 0)
function(sweep_case name stage spell difficulty cap)
  set(args --dat "${DAT}" --stage ${stage} --difficulty ${difficulty} --seed ${SEED} --frames ${cap})
  if(NOT spell LESS 0)
    list(APPEND args --spell-id ${spell})
  endif()
  execute_process(COMMAND "${EXECUTABLE}" ${args} --strategy spell-portfolio
    --actions "${WORK}/${name}.actions" --output "${WORK}/${name}.json"
    RESULT_VARIABLE code ERROR_VARIABLE error)
  if(NOT code STREQUAL "0" AND NOT code STREQUAL "2")
    message(FATAL_ERROR "${name}: native run failed: ${error}")
  endif()
  execute_process(COMMAND "${EXECUTABLE}" ${args} --replay "${WORK}/${name}.actions"
    --output "${WORK}/${name}-replay.json" RESULT_VARIABLE replay_code ERROR_VARIABLE error)
  if(NOT replay_code STREQUAL code)
    message(FATAL_ERROR "${name}: replay exit mismatch: ${error}")
  endif()
  file(READ "${WORK}/${name}.json" original)
  file(READ "${WORK}/${name}-replay.json" replay)
  agree("${original}" "${replay}")
  foreach(key IN ITEMS outcome frames trace_digest rng_draws rng_seed graze score gauge peak_bullets)
    field("${original}" "${key}" ${key})
  endforeach()
  # Timings are descriptive host measurements, never semantic replay checks.
  # Keep decision work separate from native updates and resource/file I/O.
  foreach(key IN ITEMS decision_ms simulation_ms execution_ms)
    string(REGEX MATCH "\"${key}\":[ ]*([0-9]+([.][0-9]+)?([eE][+-]?[0-9]+)?)" timing "${original}")
    if(NOT timing)
      message(FATAL_ERROR "Missing native timing ${key}")
    endif()
    set(${key} "${CMAKE_MATCH_1}")
  endforeach()
  file(SHA256 "${WORK}/${name}.actions" tape_hash)
  set(item "{\"case\":\"${name}\",\"stage\":\"${stage}\",\"spell_id\":${spell},\"difficulty\":${difficulty},\"frame_budget\":${cap},\"outcome\":${outcome},\"frames\":${frames},\"trace_digest\":${trace_digest},\"rng_draws\":${rng_draws},\"rng_seed\":${rng_seed},\"graze\":${graze},\"score\":${score},\"gauge\":${gauge},\"peak_bullets\":${peak_bullets},\"decision_ms\":${decision_ms},\"simulation_ms\":${simulation_ms},\"execution_ms\":${execution_ms},\"actions_sha256\":\"${tape_hash}\",\"fresh_replay_agrees\":true}")
  list(APPEND records "${item}")
  set(records "${records}" PARENT_SCOPE)
  math(EXPR updates "${total_updates} + 2 * ${frames}")
  set(total_updates ${updates} PARENT_SCOPE)
  if(outcome STREQUAL "\"complete\"")
    if(spell LESS 0)
      math(EXPR clears "${stage_clears} + 1")
      set(stage_clears ${clears} PARENT_SCOPE)
    else()
      math(EXPR clears "${spell_clears} + 1")
      set(spell_clears ${clears} PARENT_SCOPE)
    endif()
  endif()
  message(STATUS "${name}: ${outcome}, ${frames}; fresh replay agrees")
endfunction()
set(matrix
  "1:2,6" "2:13,17,21,25" "3:32,39,43,47" "4a:54,58,62,66,70"
  "4b:77,81,85,89,93" "5:100,104,108,112" "6a:119,123,127,131,135,139,143"
  "6b:147,151,155,159,163,167,171,175,179,183,187"
  "extra:191,192,193,194,195,196,197,198,199,200,201,202,203,204")
foreach(entry IN LISTS matrix)
  string(REPLACE ":" ";" pair "${entry}")
  list(GET pair 0 stage)
  list(GET pair 1 spells)
  string(REPLACE "," ";" spells "${spells}")
  set(difficulty 0)
  if(stage STREQUAL "extra")
    set(difficulty 4)
  endif()
  foreach(spell IN LISTS spells)
    sweep_case("spell-${spell}" "${stage}" "${spell}" ${difficulty} 15000)
  endforeach()
endforeach()
list(LENGTH records spell_count)
if(NOT spell_count EQUAL 56)
  message(FATAL_ERROR "Portfolio matrix is not the reviewed 56-case scope")
endif()
foreach(stage IN ITEMS 1 2 3 4a 4b 5 6a 6b extra)
  sweep_case("stage-${stage}" "${stage}" -1 0 100000)
endforeach()
file(SHA256 "${EXECUTABLE}" final_hash)
if(NOT final_hash STREQUAL native_hash)
  message(FATAL_ERROR "Native executable changed during sweep")
endif()
string(JOIN ",\n" records_json ${records})
cmake_host_system_information(RESULT cpu QUERY PROCESSOR_DESCRIPTION)
file(WRITE "${WORK}/summary.json"
  "{\"producer\":\"tests/headless_sweep.cmake\",\"host_processor\":\"${cpu}\",\"native_executable_sha256\":\"${native_hash}\",\"dat_sha256\":\"${dat_hash}\",\"seed\":${SEED},\"strategy\":\"spell-portfolio\",\"spell_cases\":56,\"spell_clears\":${spell_clears},\"stage_cases\":9,\"stage_clears\":${stage_clears},\"total_native_updates_including_replay\":${total_updates},\"runs\":[\n${records_json}\n]}\n")
