# Opt-in proprietary-data coverage; no asset extraction or window is involved.
# Each launch owns fresh process globals and an isolated configuration directory.
file(MAKE_DIRECTORY "${WORK}")
get_filename_component(DAT "${DAT}" ABSOLUTE)
if(LASER_ITEMS_EXECUTABLE)
  execute_process(COMMAND "${LASER_ITEMS_EXECUTABLE}" "${DAT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native laser item regression failed: ${stdout} ${stderr}")
  endif()
endif()
if(BULLET_BOUNDS_EXECUTABLE)
  execute_process(COMMAND "${BULLET_BOUNDS_EXECUTABLE}" "${DAT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native bullet bounds regression failed: ${stdout} ${stderr}")
  endif()
endif()
if(BODY_FORECAST_EXECUTABLE)
  execute_process(COMMAND "${BODY_FORECAST_EXECUTABLE}" "${DAT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native body forecast regression failed: ${stdout} ${stderr}")
  endif()
endif()
if(NOT DEFINED CASE_GROUP)
  set(CASE_GROUP all)
endif()
if(NOT CASE_GROUP MATCHES "^(all|id32|id139|id167|id183|id192|id202|id203|id204|stage6b)$")
  message(FATAL_ERROR "Unknown native case group: ${CASE_GROUP}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/headless_report_checks.cmake")

function(run exe report expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=DISPLAY --unset=WAYLAND_DISPLAY
    "${exe}" --dat "${DAT}" --output "${report}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(NOT result STREQUAL "${expected}")
    message(FATAL_ERROR "${report}: expected exit ${expected}, got ${result}: ${stdout} ${stderr}")
  endif()
endfunction()

function(scene name stage spell seed strategy budget outcome exit frames)
  set(difficulty 0)
  if(ARGC GREATER 9)
    list(GET ARGN 0 difficulty)
  endif()
  set(args --stage "${stage}" --difficulty "${difficulty}" --seed "${seed}" --frames "${budget}")
  if(NOT spell LESS 0)
    list(APPEND args --spell-id "${spell}")
  endif()
  set(tape "${WORK}/${name}.actions")
  run("${EXECUTABLE}" "${WORK}/${name}.json" "${exit}"
    ${args} --strategy "${strategy}" --actions "${tape}")
  file(READ "${WORK}/${name}.json" original)
  field("${original}" outcome actual_outcome)
  field("${original}" frames actual_frames)
  if(NOT actual_outcome STREQUAL "\"${outcome}\"" OR NOT actual_frames STREQUAL "${frames}")
    message(FATAL_ERROR "${name}: changed full-scene boundary: ${original}")
  endif()
  run("${EXECUTABLE}" "${WORK}/${name}-replay.json" "${exit}"
    ${args} --replay "${tape}")
  file(READ "${WORK}/${name}-replay.json" replay)
  agree("${original}" "${replay}")
  set(record "{\"case\":\"${name}\",\"execution\":${original},\"replay\":${replay}")
  if(COMPARE_EXECUTABLE)
    run("${COMPARE_EXECUTABLE}" "${WORK}/${name}-comparison.json" "${exit}"
      ${args} --replay "${tape}")
    file(READ "${WORK}/${name}-comparison.json" comparison)
    agree("${original}" "${comparison}")
    string(APPEND record ",\"comparison_replay\":${comparison}")
  endif()
  string(APPEND record "}")
  set(records ${records} "${record}" PARENT_SCOPE)
  message(STATUS "${name}: ${outcome}, ${frames} frames; fresh replay agrees")
endfunction()

# Separate group reports preserve useful checked evidence even if a later
# host-sensitive golden blocks the aggregate. They never replace its report.
function(write_case_group name begin)
  list(SUBLIST records ${begin} -1 group_records)
  string(JOIN ",\n" records_json ${group_records})
  cmake_host_system_information(RESULT host_cpu QUERY PROCESSOR_DESCRIPTION)
  cmake_host_system_information(RESULT host_platform QUERY OS_PLATFORM)
  set(contract_fields "")
  if(DEFINED stage6b_contract)
    string(JOIN ",\n" probe_records ${probes})
    set(comparison_checked false)
    if(COMPARE_EXECUTABLE)
      set(comparison_checked true)
    endif()
    set(contract_fields ",\"stage6b_baseline_contract\":${stage6b_contract},\"probes\":[${probe_records}],\"probe_comparison_checked\":${comparison_checked}")
  endif()
  file(WRITE "${WORK}/${name}-summary.json"
    "{\"producer\":\"tests/headless_real_data.cmake ${name} fixtures\",\"host_processor\":\"${host_cpu}\",\"host_system\":\"${CMAKE_HOST_SYSTEM_NAME}\",\"host_architecture\":\"${host_platform}\",\"runs\":[\n${records_json}\n]${contract_fields}}\n")
endfunction()

if(CASE_GROUP STREQUAL "stage6b")
  scene(stage6b-reactive 6b -1 0 reactive 50000 collision 2 854)
  include("${CMAKE_CURRENT_LIST_DIR}/headless_stage6b_checks.cmake")
  write_case_group(stage6b 0)
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id192")
  list(LENGTH records group_begin)
  scene(spell192-body-baseline extra 192 0 hazard-reactive 6000 collision 2 466 4)
  foreach(seed IN ITEMS 0 1 65535)
    if(seed EQUAL 1)
      set(outcome collision)
      set(exit 2)
      set(frames 1470)
    else()
      set(outcome complete)
      set(exit 0)
      set(frames 3692)
    endif()
    scene(spell192-portfolio-seed${seed} extra 192 ${seed} spell-portfolio 6000 ${outcome} ${exit} ${frames} 4)
    file(READ "${WORK}/spell192-portfolio-seed${seed}.json" report)
    math(EXPR candidates "${frames} * 81")
    foreach(contract IN ITEMS "policy_profile_last;\"id192-body-aware\""
                              "policy_bullet_horizon;12" "policy_first_leg_updates;1"
                              "policy_candidates;${candidates}")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID192 changed its declared body proposal budget: ${key}=${actual}")
      endif()
    endforeach()
    foreach(key IN ITEMS policy_body_warnings policy_body_envelopes policy_body_checks)
      field("${report}" "${key}" count)
      if(NOT count GREATER 0)
        message(FATAL_ERROR "ID192 never exercised ${key}")
      endif()
    endforeach()
  endforeach()
  scene(extra-portfolio extra -1 0 spell-portfolio 100000 collision 2 67738)
  file(READ "${WORK}/extra-portfolio.json" report)
  field("${report}" spell_id blocking_spell)
  if(NOT blocking_spell STREQUAL "202")
    message(FATAL_ERROR "Extra changed its retained ID202 boundary")
  endif()
  write_case_group(id192 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id192")
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id203")
  list(LENGTH records group_begin)
  scene(spell203-vector-baseline extra 203 0 hazard-reactive 6000 collision 2 1711 4)
  foreach(pair IN ITEMS "0;787" "1;787" "65535;787")
    list(GET pair 0 seed)
    list(GET pair 1 frames)
    scene(spell203-observed-beam-seed${seed} extra 203 ${seed} spell-portfolio 6000 collision 2 ${frames} 4)
    file(READ "${WORK}/spell203-observed-beam-seed${seed}.json" report)
    field("${report}" policy_wait_vector_checks count)
    if(NOT count GREATER 0)
      message(FATAL_ERROR "ID203 never exercised its bounded WAIT/vector view")
    endif()
  endforeach()
  # Strict replay must not silently become prefix continuation.
  file(STRINGS "${WORK}/spell203-observed-beam-seed0.actions" prefix LIMIT_COUNT 50)
  string(JOIN "\n" prefix_text ${prefix})
  file(WRITE "${WORK}/id203-control.prefix" "${prefix_text}\n")
  set(args --stage extra --spell-id 203 --difficulty 4 --seed 0 --frames 6000)
  run("${EXECUTABLE}" "${WORK}/id203-short-replay.json" 2 ${args}
    --replay "${WORK}/id203-control.prefix")
  file(READ "${WORK}/id203-short-replay.json" short_replay)
  field("${short_replay}" outcome short_outcome)
  field("${short_replay}" frames short_frames)
  if(NOT short_outcome STREQUAL "\"tape_end\"" OR NOT short_frames STREQUAL "50")
    message(FATAL_ERROR "Strict replay silently continued beyond its tape")
  endif()
  run("${EXECUTABLE}" "${WORK}/id203-resume.json" 2 ${args} --strategy spell-portfolio
    --resume-prefix "${WORK}/id203-control.prefix" --actions "${WORK}/id203-resume.actions")
  file(READ "${WORK}/id203-resume.json" resumed)
  file(READ "${WORK}/spell203-observed-beam-seed0.json" initial)
  agree("${initial}" "${resumed}")
  file(SHA256 "${WORK}/id203-resume.actions" resumed_tape)
  file(SHA256 "${WORK}/spell203-observed-beam-seed0.actions" initial_tape)
  if(NOT resumed_tape STREQUAL initial_tape)
    message(FATAL_ERROR "Native prefix continuation changed the control tape")
  endif()
  if(REPAIR_EXECUTABLE)
    set(repair_search_reused false)
    if(REPAIR_RESULT_DIR)
      set(repair_search_reused true)
      set(directory "${REPAIR_RESULT_DIR}")
      file(READ "${directory}/summary.json" cached_search)
      field("${cached_search}" child_executable_sha256 cached_child)
      field("${cached_search}" repair_executable_sha256 cached_repair)
      file(SHA256 "${EXECUTABLE}" current_child)
      file(SHA256 "${REPAIR_EXECUTABLE}" current_repair)
      if(NOT cached_child STREQUAL "\"${current_child}\"" OR
          NOT cached_repair STREQUAL "\"${current_repair}\"")
        message(FATAL_ERROR "Existing repair results belong to different executable bytes")
      endif()
    else()
      set(directory "${WORK}/id203-repair")
      file(REMOVE_RECURSE "${directory}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=DISPLAY --unset=WAYLAND_DISPLAY
      "${REPAIR_EXECUTABLE}" --executable "${EXECUTABLE}" --dat "${DAT}"
      --stage extra --spell-id 203 --difficulty 4 --seed 0 --frames 15000 --seconds 600
      --output-dir "${directory}" RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "Bounded native repair failed: ${result}: ${stdout}${stderr}")
    endif()
    endif()
    file(READ "${directory}/summary.json" search)
    field("${search}" outcome repair_outcome)
    if(NOT repair_outcome STREQUAL "\"complete\"")
      message(FATAL_ERROR "Repair artifact is not a complete verified search")
    endif()
    field("${search}" selected_case selected)
    string(REPLACE "\"" "" selected "${selected}")
    file(READ "${directory}/${selected}.json" original)
    field("${original}" frames frames)
    field("${original}" prefix_frame prefix_frame)
    if(NOT frames STREQUAL "5492")
      message(FATAL_ERROR "ID203 repair changed complete wrapper boundary")
    endif()
    set(args --stage extra --spell-id 203 --difficulty 4 --seed 0 --frames 15000
      --prefix-frame "${prefix_frame}" --replay "${directory}/${selected}.actions")
    run("${EXECUTABLE}" "${WORK}/id203-repaired-replay.json" 0 ${args})
    file(READ "${WORK}/id203-repaired-replay.json" replay)
    agree("${original}" "${replay}")
    set(record "{\"case\":\"spell203-bounded-native-repair\",\"execution\":${original},\"replay\":${replay},\"search\":${search},\"search_reused\":${repair_search_reused}")
    if(COMPARE_EXECUTABLE)
      run("${COMPARE_EXECUTABLE}" "${WORK}/id203-repaired-comparison.json" 0 ${args})
      file(READ "${WORK}/id203-repaired-comparison.json" comparison)
      agree("${original}" "${comparison}")
      string(APPEND record ",\"comparison_replay\":${comparison}")
    endif()
    string(APPEND record "}")
    list(APPEND records "${record}")
    message(STATUS "ID203 bounded native repair: complete5492; fresh replay agrees")
  endif()
  write_case_group(id203 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id203")
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id32")
  list(LENGTH records group_begin)
  # The extra observed update and one-update leg are explicit planning costs.
  scene(spell32-corner-baseline 3 32 0 hazard-reactive 15000 collision 2 594)
  foreach(seed IN ITEMS 0 1 65535)
    scene(spell32-portfolio-seed${seed} 3 32 ${seed} spell-portfolio 15000 complete 0 2372)
    file(READ "${WORK}/spell32-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id32-two-leg-corner\""
                              "policy_bullet_horizon;13" "policy_first_leg_updates;1"
                              "policy_candidates;192132")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID32 changed its declared maneuver budget: ${key}=${actual}")
      endif()
    endforeach()
  endforeach()
  scene(stage3-corner-baseline 3 -1 0 hazard-reactive 100000 collision 2 7443)
  scene(stage3-portfolio 3 -1 0 spell-portfolio 100000 complete 0 39767)
  write_case_group(id32 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id32")
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id167")
  list(LENGTH records group_begin)
  scene(spell167-corner-baseline 6b 167 0 hazard-reactive 15000 collision 2 932)
  foreach(seed IN ITEMS 0 1 65535)
    scene(spell167-portfolio-seed${seed} 6b 167 ${seed} spell-portfolio 15000 complete 0 5492)
    file(READ "${WORK}/spell167-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id167-two-leg-corner\""
                              "policy_bullet_horizon;12" "policy_first_leg_updates;4"
                              "policy_candidates;444852")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID167 changed its declared maneuver budget: ${key}=${actual}")
      endif()
    endforeach()
  endforeach()
  write_case_group(id167 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id167")
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id183")
  list(LENGTH records group_begin)
  scene(spell183-large-bullet-baseline 6b 183 0 hazard-reactive 15000 collision 2 1041)
  foreach(seed IN ITEMS 0 1 65535)
    scene(spell183-portfolio-seed${seed} 6b 183 ${seed} spell-portfolio 15000 complete 0 1292)
    file(READ "${WORK}/spell183-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id183-two-leg-large-bullet\""
                              "policy_bullet_horizon;32" "policy_first_leg_updates;4"
                              "policy_candidates;104652")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID183 changed its declared maneuver budget: ${key}=${actual}")
      endif()
    endforeach()
  endforeach()
  # This is the current carried-stage gate; the preceding ID167 profile stopped
  # at ID183 update 54401, retained in the preceding-checkpoint comparison.
  scene(stage6b-portfolio 6b -1 0 spell-portfolio 100000 complete 0 58853)
  write_case_group(id183 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id183")
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id139")
  list(LENGTH records group_begin)
  # Preserve source-vector failures in the wrapper and the continuous stage.
  scene(spell139-bounce-baseline 6a 139 0 hazard-reactive 15000 collision 2 5326)
  file(READ "${WORK}/spell139-bounce-baseline.json" baseline139)
  foreach(pair IN ITEMS "bullet_slot;851" "active_transforms;2048")
    list(GET pair 0 key)
    list(GET pair 1 expected)
    field("${baseline139}" "${key}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "ID139 changed its preserved bounce boundary")
    endif()
  endforeach()
  foreach(seed IN ITEMS 0 1 65535)
    scene(spell139-portfolio-seed${seed} 6a 139 ${seed} spell-portfolio 15000 complete 0 7292)
    file(READ "${WORK}/spell139-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id139-two-leg-bounce\""
                              "policy_bullet_horizon;32" "policy_first_leg_updates;4"
                              "policy_candidates;590652")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID139 changed its declared model/budget: ${key}=${actual}")
      endif()
    endforeach()
    field("${report}" policy_boundary_bounce_checks checks)
    if(NOT checks GREATER 0)
      message(FATAL_ERROR "ID139 never exercised its source bounce projection")
    endif()
  endforeach()
  scene(stage6a-vector-baseline 6a -1 0 hazard-reactive 100000 collision 2 48302)
  scene(stage6a-portfolio 6a -1 0 spell-portfolio 100000 complete 0 61041)
  write_case_group(id139 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id139")
  return()
endif()

if(NOT CASE_GROUP STREQUAL "id204")
  list(LENGTH records group_begin)
  # ID202's first collision is an already-born random child executing WAIT.
  # The opt-in removes that local mistake but retains the later emission failure;
  # no random future is sampled or treated as an empty deterministic preview.
  scene(spell202-wait-baseline extra 202 0 hazard-reactive 6000 collision 2 3265 4)
  file(READ "${WORK}/spell202-wait-baseline.json" spell202_baseline)
  foreach(pair IN ITEMS "bullet_slot;1369" "active_transforms;131072")
    list(GET pair 0 key)
    list(GET pair 1 expected)
    field("${spell202_baseline}" "${key}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "ID202 changed its preserved WAIT boundary: ${key}=${actual}")
    endif()
  endforeach()
  foreach(pair IN ITEMS "0;4204" "1;4216" "65535;3613")
    list(GET pair 0 seed)
    list(GET pair 1 frames)
    scene(spell202-portfolio-seed${seed} extra 202 ${seed} spell-portfolio 6000 collision 2 ${frames} 4)
    file(READ "${WORK}/spell202-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id202-observed-wait\""
                              "policy_bullet_horizon;12" "policy_upcoming_bullet_decisions;0")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID202 crossed its observed-WAIT contract: ${key}=${actual}")
      endif()
    endforeach()
    field("${report}" policy_wait_linear_checks checks)
    if(NOT checks GREATER 0)
      message(FATAL_ERROR "ID202 never exercised bounded WAIT")
    endif()
  endforeach()
  if(REPAIR_EXECUTABLE)
    # Search derives its branch from the failure trace. The test checks the
    # complete wrapper and replay, never supplies a known winning frame/action.
    set(directory "${WORK}/id202-repair")
    file(REMOVE_RECURSE "${directory}")
    execute_process(COMMAND "${REPAIR_EXECUTABLE}" --executable "${EXECUTABLE}" --dat "${DAT}"
      --stage extra --spell-id 202 --difficulty 4 --seed 0 --frames 15000 --seconds 600
      --output-dir "${directory}" RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "ID202 native repair failed: ${result}: ${stdout}${stderr}")
    endif()
    file(READ "${directory}/summary.json" search)
    field("${search}" selected_case selected)
    string(REPLACE "\"" "" selected "${selected}")
    file(READ "${directory}/${selected}.json" original)
    field("${original}" frames frames)
    field("${original}" prefix_frame prefix_frame)
    if(NOT frames STREQUAL "4712")
      message(FATAL_ERROR "ID202 repair changed complete wrapper boundary")
    endif()
    set(args --stage extra --spell-id 202 --difficulty 4 --seed 0 --frames 15000
      --prefix-frame "${prefix_frame}" --replay "${directory}/${selected}.actions")
    run("${EXECUTABLE}" "${WORK}/id202-repaired-replay.json" 0 ${args})
    file(READ "${WORK}/id202-repaired-replay.json" replay)
    agree("${original}" "${replay}")
    set(record "{\"case\":\"spell202-bounded-native-repair\",\"execution\":${original},\"replay\":${replay},\"search\":${search}")
    if(COMPARE_EXECUTABLE)
      run("${COMPARE_EXECUTABLE}" "${WORK}/id202-repaired-comparison.json" 0 ${args})
      file(READ "${WORK}/id202-repaired-comparison.json" comparison)
      agree("${original}" "${comparison}")
      string(APPEND record ",\"comparison_replay\":${comparison}")
    endif()
    string(APPEND record "}")
    list(APPEND records "${record}")
    message(STATUS "ID202 bounded native repair: complete4712; fresh replay agrees")
  endif()
  write_case_group(id202 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id202")
  return()
endif()

# ID204 decelerates throughout its active relative-direction interval.
# Preserve the unsupported baseline and a failed seed, rather than treating
# this bounded transform model as a complete future program interpreter.
list(LENGTH records group_begin)
scene(spell204-relative-baseline extra 204 0 hazard-reactive 6000 collision 2 1205 4)
file(READ "${WORK}/spell204-relative-baseline.json" baseline204)
foreach(pair IN ITEMS "bullet_slot;669" "active_transforms;64")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${baseline204}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID204 changed its preserved relative-direction boundary")
  endif()
endforeach()
foreach(seed IN ITEMS 0 65535)
  scene(spell204-portfolio-seed${seed} extra 204 ${seed} spell-portfolio 6000 complete 0 4832 4)
endforeach()
scene(spell204-portfolio-seed1 extra 204 1 spell-portfolio 6000 collision 2 3008 4)
foreach(seed IN ITEMS 0 1 65535)
  file(READ "${WORK}/spell204-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_bullet_horizon horizon)
  field("${report}" policy_relative_direction_checks checks)
  if(NOT profile STREQUAL "\"id204-relative-direction\"" OR NOT horizon STREQUAL "12" OR
     NOT checks GREATER 0)
    message(FATAL_ERROR "ID204 lost its bounded source projection")
  endif()
endforeach()
write_case_group(id204 ${group_begin})
if(CASE_GROUP STREQUAL "id204")
  return()
endif()

scene(stage1 1 -1 0 reactive 30000 complete 0 22176)
foreach(seed IN ITEMS 0 1 65535)
  scene(spell179-seed${seed} 6b 179 ${seed} reactive 2000 complete 0 1292)
endforeach()
# Preserve a genuine bad strategy and a bounded run as failures, including replay.
scene(spell179-stationary 6b 179 0 stationary 2000 collision 2 382)
scene(stage1-budget 1 -1 0 reactive 10 frame_limit 2 10)
scene(stage6b-reactive 6b -1 0 reactive 50000 collision 2 854)
# ID85 rotates and translates live pooled lasers from ECL. Preserve the static
# forecast failure, then require the isolated observed rigid-motion profile.
scene(spell85-pooled-laser-baseline 4b 85 0 hazard-reactive 1000 collision 2 631)
file(READ "${WORK}/spell85-pooled-laser-baseline.json" spell85)
foreach(pair IN ITEMS "laser_slot;7" "laser_hitbox_call;4")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell85}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID85 changed pooled-laser source: ${spell85}")
  endif()
endforeach()
foreach(seed IN ITEMS 0 1 65535)
  scene(spell85-portfolio-seed${seed} 4b 85 ${seed} spell-portfolio 4000 complete 0 2792)
  file(READ "${WORK}/spell85-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_rigid_laser_paths rigid_paths)
  if(NOT profile STREQUAL "\"id85-rigid-laser-motion\"" OR NOT rigid_paths GREATER 0)
    message(FATAL_ERROR "ID85 did not exercise its pooled-laser motion model: ${report}")
  endif()
endforeach()
# Preserve the unadapted ID89 failure: its rotating beam is an ECL-owned
# CalcLaserHitbox call rather than a BulletManager laser.
scene(spell89-direct-laser-baseline 4b 89 0 hazard-reactive 1000 collision 2 393)
file(READ "${WORK}/spell89-direct-laser-baseline.json" spell89)
foreach(pair IN ITEMS "laser_slot;-1" "laser_hitbox_call;0")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell89}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID89 direct-laser ${key} changed: ${actual}")
  endif()
endforeach()
run("${EXECUTABLE}" "${WORK}/spell89-direct-laser-diagnostic.json" 2
  --stage 4b --spell-id 89 --difficulty 0 --seed 0 --frames 1000
  --replay "${WORK}/spell89-direct-laser-baseline.actions" --trace "${WORK}/spell89.tsv")
file(READ "${WORK}/spell89-direct-laser-diagnostic.json" spell89_diagnostic)
agree("${spell89}" "${spell89_diagnostic}")
file(STRINGS "${WORK}/spell89.tsv" direct_hitbox
  REGEX "^393.*after.*laser_hitbox.*-1")
if(NOT direct_hitbox)
  message(FATAL_ERROR "ID89 direct ECL hitbox was absent from the diagnostic trace")
endif()
foreach(seed IN ITEMS 0 1 65535)
  scene(spell89-portfolio-seed${seed} 4b 89 ${seed} spell-portfolio 4000 complete 0 3162)
  file(READ "${WORK}/spell89-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_direct_laser_constrained_decisions constrained)
  if(NOT profile STREQUAL "\"id89-direct-ecl-laser\"" OR NOT constrained GREATER 0)
    message(FATAL_ERROR "ID89 did not exercise its ECL candidate constraint: ${report}")
  endif()
endforeach()
# ID93 creates a one-frame-startup pooled laser after the policy decision. By
# the first observed LaserView, input latency makes the measured hit unavoidable.
# Preserve that failure and require a source-decoded, currently due opcode-114
# warning with no unsupported future substituted into the three seeded runs.
scene(spell93-pooled-laser-baseline 4b 93 0 hazard-reactive 2000 collision 2 1539)
file(READ "${WORK}/spell93-pooled-laser-baseline.json" spell93)
foreach(pair IN ITEMS "laser_slot;0" "laser_hitbox_call;0")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell93}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID93 changed imminent pooled-laser source: ${spell93}")
  endif()
endforeach()
foreach(seed IN ITEMS 0 1 65535)
  scene(spell93-portfolio-seed${seed} 4b 93 ${seed} spell-portfolio 5000 complete 0 3392)
  file(READ "${WORK}/spell93-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_imminent_laser_due_spawns due)
  field("${report}" policy_imminent_laser_warnings warnings)
  field("${report}" policy_imminent_laser_unsupported_spawns unsupported)
  field("${report}" policy_imminent_laser_constrained_decisions constrained)
  if(NOT profile STREQUAL "\"id93-imminent-pooled-laser\"" OR
     NOT due STREQUAL "82" OR NOT warnings STREQUAL "82" OR
     NOT unsupported STREQUAL "0" OR NOT constrained GREATER 0)
    message(FATAL_ERROR "ID93 did not exercise its source-owned spawn warning: ${report}")
  endif()
endforeach()
# ID198's fixed-origin beam requires the same observed rotation model as ID85,
# but constant paths oscillate into a later bullet/beam trap. Preserve that
# first failure and require the isolated two-leg proposal set through spell end.
scene(spell198-pooled-laser-baseline extra 198 0 hazard-reactive 1000 collision 2 446 4)
file(READ "${WORK}/spell198-pooled-laser-baseline.json" spell198)
foreach(pair IN ITEMS "laser_slot;0" "laser_hitbox_call;0")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell198}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID198 changed pooled-laser source: ${spell198}")
  endif()
endforeach()
foreach(seed IN ITEMS 0 1 65535)
  scene(spell198-portfolio-seed${seed} extra 198 ${seed} spell-portfolio 6000 complete 0 4292 4)
  file(READ "${WORK}/spell198-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_first_leg_updates first_leg)
  field("${report}" policy_rigid_laser_paths rigid_paths)
  field("${report}" policy_bullet_projections projections)
  if(NOT profile STREQUAL "\"id198-two-leg-rigid-laser\"" OR
     NOT first_leg STREQUAL "4" OR NOT rigid_paths GREATER 0 OR NOT projections GREATER 0)
    message(FATAL_ERROR "ID198 did not exercise its two-leg cached forecast: ${report}")
  endif()
endforeach()
# ID201's first unadapted collision is a large parent still executing WAIT.
# Preserve that source boundary, then require the isolated adapter to exercise
# both the source-bounded WAIT path and deterministic future opcode-97 shots.
scene(spell201-wait-baseline extra 201 0 hazard-reactive 1000 collision 2 362 4)
file(READ "${WORK}/spell201-wait-baseline.json" spell201)
foreach(pair IN ITEMS "bullet_slot;24" "active_transforms;131072")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell201}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID201 changed delayed-bullet ${key}: ${actual}")
  endif()
endforeach()
scene(spell201-portfolio-seed0 extra 201 0 spell-portfolio 6000 complete 0 4292 4)
file(READ "${WORK}/spell201-portfolio-seed0.json" spell201_portfolio)
foreach(pair IN ITEMS "policy_profile_last;\"id201-wait-and-ecl-shot\""
                      "policy_bullet_horizon;32"
                      "policy_upcoming_bullet_unsupported_spawns;0")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell201_portfolio}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID201 changed ${key}: ${actual}")
  endif()
endforeach()
foreach(key IN ITEMS policy_wait_linear_checks policy_upcoming_bullet_observed_spawns
                     policy_upcoming_bullet_warnings
                     policy_upcoming_bullet_constrained_decisions)
  field("${spell201_portfolio}" "${key}" actual)
  if(NOT actual GREATER 0)
    message(FATAL_ERROR "ID201 did not exercise ${key}: ${spell201_portfolio}")
  endif()
endforeach()
# Distinct spell profiles guard the measured portfolio boundary. ID195 needs
# vector acceleration; ID199 deliberately retains constant-velocity ranking.
scene(spell193-portfolio extra 193 0 spell-portfolio 5000 complete 0 3692 4)
scene(spell195-portfolio extra 195 0 spell-portfolio 6000 complete 0 4712 4)
scene(spell199-portfolio extra 199 0 spell-portfolio 5000 complete 0 4292 4)
foreach(pair IN ITEMS "spell193-portfolio;source-vector-ranking"
                      "spell195-portfolio;source-vector-ranking"
                      "spell199-portfolio;id199-linear-ranking")
  list(GET pair 0 name)
  list(GET pair 1 expected)
  file(READ "${WORK}/${name}.json" report)
  field("${report}" policy_profile_last actual)
  if(NOT actual STREQUAL "\"${expected}\"")
    message(FATAL_ERROR "${name}: selected ${actual}, expected ${expected}")
  endif()
endforeach()

include("${CMAKE_CURRENT_LIST_DIR}/headless_stage6b_checks.cmake")

file(WRITE "${WORK}/illegal.actions" "32768\n")
run("${EXECUTABLE}" "${WORK}/illegal.json" 1 --replay "${WORK}/illegal.actions")
file(READ "${WORK}/stage1-budget.actions" prefix)
file(WRITE "${WORK}/excess.actions" "${prefix}4\n")
run("${EXECUTABLE}" "${WORK}/excess.json" 1 --frames 10 --replay "${WORK}/excess.actions")
# Explicit diagnostic suffix truncation stays a frame-limit failure and reports
# the unused input. Strict replay above still rejects the same tape by default.
run("${EXECUTABLE}" "${WORK}/bounded-prefix.json" 2 --frames 10
  --replay "${WORK}/excess.actions" --allow-unused-actions 1)
file(READ "${WORK}/bounded-prefix.json" bounded)
field("${bounded}" unused_actions unused)
if(NOT unused STREQUAL "1")
  message(FATAL_ERROR "Unused diagnostic suffix was not recorded")
endif()
execute_process(COMMAND "${PROBE_EXECUTABLE}" --executable "${EXECUTABLE}"
  --dat "${DAT}" --actions "${stage6_tape}" --frame 855 --output-dir "${WORK}/invalid-probe"
  RESULT_VARIABLE invalid_probe OUTPUT_QUIET ERROR_QUIET)
if(NOT invalid_probe STREQUAL "1")
  message(FATAL_ERROR "An out-of-tape intervention was accepted")
endif()
# An engine practice wrapper can choose another raw ID for an invalid stage/ID pair.
run("${EXECUTABLE}" "${WORK}/wrong-checkpoint.json" 1
  --stage 6b --spell-id 178 --strategy reactive --frames 2000)

string(JOIN ",\n" records_json ${records})
string(JOIN ",\n" probes_json ${probes})
set(probe_comparison_checked false)
if(COMPARE_EXECUTABLE)
  set(probe_comparison_checked true)
endif()
cmake_host_system_information(RESULT host_cpu QUERY PROCESSOR_DESCRIPTION)
cmake_host_system_information(RESULT host_platform QUERY OS_PLATFORM)
file(WRITE "${WORK}/summary.json"
  "{\"producer\":\"tests/headless_real_data.cmake + th08_headless + th08_headless_probe\",\"host_processor\":\"${host_cpu}\",\"host_system\":\"${CMAKE_HOST_SYSTEM_NAME}\",\"host_architecture\":\"${host_platform}\",\"runs\":[\n${records_json}\n],\"probes\":[\n${probes_json}\n],\"stage6b_baseline_contract\":${stage6b_contract},\"illegal_input_rejected\":true,\"excess_tape_rejected\":true,\"wrong_checkpoint_rejected\":true,\"invalid_probe_rejected\":true,\"diagnostics_preserve_trajectory\":true,\"probe_comparison_checked\":${probe_comparison_checked}}\n")
