# Opt-in proprietary-data coverage; no asset extraction or window is involved.
# Each launch owns fresh process globals and an isolated configuration directory.
file(MAKE_DIRECTORY "${WORK}")
get_filename_component(DAT "${DAT}" ABSOLUTE)
if(LASER_ITEMS_EXECUTABLE)
  execute_process(COMMAND "${LASER_ITEMS_EXECUTABLE}" "${DAT}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native laser item regression failed: ${stdout} ${stderr}")
  endif()
endif()
if(NOT DEFINED CASE_GROUP)
  set(CASE_GROUP all)
endif()
if(NOT CASE_GROUP MATCHES "^(all|id32|id139|id167|id183|id202|id204)$")
  message(FATAL_ERROR "Unknown native case group: ${CASE_GROUP}")
endif()

function(field report key result)
  string(REGEX MATCH "\"${key}\":[ ]*(\"[^\"]*\"|-?[0-9]+)" match "${report}")
  if(NOT match)
    message(FATAL_ERROR "Missing report field ${key}")
  endif()
  set(${result} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

function(run exe report expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=DISPLAY --unset=WAYLAND_DISPLAY
    "${exe}" --dat "${DAT}" --output "${report}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(NOT result STREQUAL "${expected}")
    message(FATAL_ERROR "${report}: expected exit ${expected}, got ${result}: ${stdout} ${stderr}")
  endif()
endfunction()

function(agree left right)
  # Compare execution feedback and the frame-by-frame projection, not timings.
  foreach(key IN ITEMS source_revision profile dat_sha256 stage requested_spell_id difficulty
      seed frame_budget outcome frames spell_id spell_start first_hit deaths player_state
      rng_draws rng_seed graze score gauge peak_bullets trace_digest previous_trace_digest
      prefix_frame prefix_trace_digest unused_actions)
    field("${left}" "${key}" a)
    field("${right}" "${key}" b)
    if(NOT a STREQUAL b)
      message(FATAL_ERROR "Fresh replay diverged at ${key}: ${a} vs ${b}")
    endif()
  endforeach()
  string(REGEX MATCH "\"collision\":\\{[^}]+\\}" a "${left}")
  string(REGEX MATCH "\"collision\":\\{[^}]+\\}" b "${right}")
  if(NOT a OR NOT a STREQUAL b)
    message(FATAL_ERROR "Fresh replay collision diagnostics diverged: ${a} vs ${b}")
  endif()
endfunction()

function(scene name stage spell seed strategy budget outcome exit frames)
  set(difficulty 0)
  if(ARGC GREATER 9)
    list(GET ARGN 0 difficulty)
  endif()
  set(args --stage "${stage}" --difficulty "${difficulty}" --seed "${seed}" --frames "${budget}")
  if(NOT spell LESS 0)
    list(APPEND args --spell-id "${spell}")
  endif()
  set(tape "${WORK}/${name}.actions")
  run("${EXECUTABLE}" "${WORK}/${name}.json" "${exit}"
    ${args} --strategy "${strategy}" --actions "${tape}")
  file(READ "${WORK}/${name}.json" original)
  field("${original}" outcome actual_outcome)
  field("${original}" frames actual_frames)
  if(NOT actual_outcome STREQUAL "\"${outcome}\"" OR NOT actual_frames STREQUAL "${frames}")
    message(FATAL_ERROR "${name}: changed full-scene boundary: ${original}")
  endif()
  run("${EXECUTABLE}" "${WORK}/${name}-replay.json" "${exit}"
    ${args} --replay "${tape}")
  file(READ "${WORK}/${name}-replay.json" replay)
  agree("${original}" "${replay}")
  set(record "{\"case\":\"${name}\",\"execution\":${original},\"replay\":${replay}")
  if(COMPARE_EXECUTABLE)
    run("${COMPARE_EXECUTABLE}" "${WORK}/${name}-comparison.json" "${exit}"
      ${args} --replay "${tape}")
    file(READ "${WORK}/${name}-comparison.json" comparison)
    agree("${original}" "${comparison}")
    string(APPEND record ",\"comparison_replay\":${comparison}")
  endif()
  string(APPEND record "}")
  set(records ${records} "${record}" PARENT_SCOPE)
  message(STATUS "${name}: ${outcome}, ${frames} frames; fresh replay agrees")
endfunction()

# Separate group reports preserve useful checked evidence even if a later
# host-sensitive golden blocks the aggregate. They never replace its report.
function(write_case_group name begin)
  list(SUBLIST records ${begin} -1 group_records)
  string(JOIN ",\n" records_json ${group_records})
  cmake_host_system_information(RESULT host_cpu QUERY PROCESSOR_DESCRIPTION)
  cmake_host_system_information(RESULT host_platform QUERY OS_PLATFORM)
  file(WRITE "${WORK}/${name}-summary.json"
    "{\"producer\":\"tests/headless_real_data.cmake ${name} fixtures\",\"host_processor\":\"${host_cpu}\",\"host_system\":\"${CMAKE_HOST_SYSTEM_NAME}\",\"host_architecture\":\"${host_platform}\",\"runs\":[\n${records_json}\n]}\n")
endfunction()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id32")
  list(LENGTH records group_begin)
  # The extra observed update and one-update leg are explicit planning costs.
  scene(spell32-corner-baseline 3 32 0 hazard-reactive 15000 collision 2 594)
  foreach(seed IN ITEMS 0 1 65535)
    scene(spell32-portfolio-seed${seed} 3 32 ${seed} spell-portfolio 15000 complete 0 2372)
    file(READ "${WORK}/spell32-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id32-two-leg-corner\""
                              "policy_bullet_horizon;13" "policy_first_leg_updates;1"
                              "policy_candidates;192132")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID32 changed its declared maneuver budget: ${key}=${actual}")
      endif()
    endforeach()
  endforeach()
  scene(stage3-corner-baseline 3 -1 0 hazard-reactive 100000 collision 2 7443)
  scene(stage3-portfolio 3 -1 0 spell-portfolio 100000 complete 0 39767)
  write_case_group(id32 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id32")
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id167")
  list(LENGTH records group_begin)
  scene(spell167-corner-baseline 6b 167 0 hazard-reactive 15000 collision 2 932)
  foreach(seed IN ITEMS 0 1 65535)
    scene(spell167-portfolio-seed${seed} 6b 167 ${seed} spell-portfolio 15000 complete 0 5492)
    file(READ "${WORK}/spell167-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id167-two-leg-corner\""
                              "policy_bullet_horizon;12" "policy_first_leg_updates;4"
                              "policy_candidates;444852")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID167 changed its declared maneuver budget: ${key}=${actual}")
      endif()
    endforeach()
  endforeach()
  write_case_group(id167 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id167")
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id183")
  list(LENGTH records group_begin)
  scene(spell183-large-bullet-baseline 6b 183 0 hazard-reactive 15000 collision 2 1041)
  foreach(seed IN ITEMS 0 1 65535)
    scene(spell183-portfolio-seed${seed} 6b 183 ${seed} spell-portfolio 15000 complete 0 1292)
    file(READ "${WORK}/spell183-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id183-two-leg-large-bullet\""
                              "policy_bullet_horizon;32" "policy_first_leg_updates;4"
                              "policy_candidates;104652")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID183 changed its declared maneuver budget: ${key}=${actual}")
      endif()
    endforeach()
  endforeach()
  # This is the current carried-stage gate; the preceding ID167 profile stopped
  # at ID183 update 54401, retained in the preceding-checkpoint comparison.
  scene(stage6b-portfolio 6b -1 0 spell-portfolio 100000 complete 0 58853)
  write_case_group(id183 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id183")
  return()
endif()

if(CASE_GROUP STREQUAL "all" OR CASE_GROUP STREQUAL "id139")
  list(LENGTH records group_begin)
  # Preserve source-vector failures in the wrapper and the continuous stage.
  scene(spell139-bounce-baseline 6a 139 0 hazard-reactive 15000 collision 2 5326)
  file(READ "${WORK}/spell139-bounce-baseline.json" baseline139)
  foreach(pair IN ITEMS "bullet_slot;851" "active_transforms;2048")
    list(GET pair 0 key)
    list(GET pair 1 expected)
    field("${baseline139}" "${key}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "ID139 changed its preserved bounce boundary")
    endif()
  endforeach()
  foreach(seed IN ITEMS 0 1 65535)
    scene(spell139-portfolio-seed${seed} 6a 139 ${seed} spell-portfolio 15000 complete 0 7292)
    file(READ "${WORK}/spell139-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id139-two-leg-bounce\""
                              "policy_bullet_horizon;32" "policy_first_leg_updates;4"
                              "policy_candidates;590652")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID139 changed its declared model/budget: ${key}=${actual}")
      endif()
    endforeach()
    field("${report}" policy_boundary_bounce_checks checks)
    if(NOT checks GREATER 0)
      message(FATAL_ERROR "ID139 never exercised its source bounce projection")
    endif()
  endforeach()
  scene(stage6a-vector-baseline 6a -1 0 hazard-reactive 100000 collision 2 48302)
  scene(stage6a-portfolio 6a -1 0 spell-portfolio 100000 complete 0 61041)
  write_case_group(id139 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id139")
  return()
endif()

if(NOT CASE_GROUP STREQUAL "id204")
  list(LENGTH records group_begin)
  # ID202's first collision is an already-born random child executing WAIT.
  # The opt-in removes that local mistake but retains the later emission failure;
  # no random future is sampled or treated as an empty deterministic preview.
  scene(spell202-wait-baseline extra 202 0 hazard-reactive 6000 collision 2 3265 4)
  file(READ "${WORK}/spell202-wait-baseline.json" spell202_baseline)
  foreach(pair IN ITEMS "bullet_slot;1369" "active_transforms;131072")
    list(GET pair 0 key)
    list(GET pair 1 expected)
    field("${spell202_baseline}" "${key}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "ID202 changed its preserved WAIT boundary: ${key}=${actual}")
    endif()
  endforeach()
  foreach(pair IN ITEMS "0;4204" "1;4216" "65535;3613")
    list(GET pair 0 seed)
    list(GET pair 1 frames)
    scene(spell202-portfolio-seed${seed} extra 202 ${seed} spell-portfolio 6000 collision 2 ${frames} 4)
    file(READ "${WORK}/spell202-portfolio-seed${seed}.json" report)
    foreach(contract IN ITEMS "policy_profile_last;\"id202-observed-wait\""
                              "policy_bullet_horizon;12" "policy_upcoming_bullet_decisions;0")
      list(GET contract 0 key)
      list(GET contract 1 expected)
      field("${report}" "${key}" actual)
      if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "ID202 crossed its observed-WAIT contract: ${key}=${actual}")
      endif()
    endforeach()
    field("${report}" policy_wait_linear_checks checks)
    if(NOT checks GREATER 0)
      message(FATAL_ERROR "ID202 never exercised bounded WAIT")
    endif()
  endforeach()
  write_case_group(id202 ${group_begin})
endif()
if(CASE_GROUP STREQUAL "id202")
  return()
endif()

# ID204 decelerates throughout its active relative-direction interval.
# Preserve the unsupported baseline and a failed seed, rather than treating
# this bounded transform model as a complete future program interpreter.
list(LENGTH records group_begin)
scene(spell204-relative-baseline extra 204 0 hazard-reactive 6000 collision 2 1205 4)
file(READ "${WORK}/spell204-relative-baseline.json" baseline204)
foreach(pair IN ITEMS "bullet_slot;669" "active_transforms;64")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${baseline204}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID204 changed its preserved relative-direction boundary")
  endif()
endforeach()
foreach(seed IN ITEMS 0 65535)
  scene(spell204-portfolio-seed${seed} extra 204 ${seed} spell-portfolio 6000 complete 0 4832 4)
endforeach()
scene(spell204-portfolio-seed1 extra 204 1 spell-portfolio 6000 collision 2 3008 4)
foreach(seed IN ITEMS 0 1 65535)
  file(READ "${WORK}/spell204-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_bullet_horizon horizon)
  field("${report}" policy_relative_direction_checks checks)
  if(NOT profile STREQUAL "\"id204-relative-direction\"" OR NOT horizon STREQUAL "12" OR
     NOT checks GREATER 0)
    message(FATAL_ERROR "ID204 lost its bounded source projection")
  endif()
endforeach()
write_case_group(id204 ${group_begin})
if(CASE_GROUP STREQUAL "id204")
  return()
endif()

scene(stage1 1 -1 0 reactive 30000 complete 0 22176)
foreach(seed IN ITEMS 0 1 65535)
  scene(spell179-seed${seed} 6b 179 ${seed} reactive 2000 complete 0 1292)
endforeach()
# Preserve a genuine bad strategy and a bounded run as failures, including replay.
scene(spell179-stationary 6b 179 0 stationary 2000 collision 2 382)
scene(stage1-budget 1 -1 0 reactive 10 frame_limit 2 10)
scene(stage6b-reactive 6b -1 0 reactive 50000 collision 2 854)
# ID85 rotates and translates live pooled lasers from ECL. Preserve the static
# forecast failure, then require the isolated observed rigid-motion profile.
scene(spell85-pooled-laser-baseline 4b 85 0 hazard-reactive 1000 collision 2 631)
file(READ "${WORK}/spell85-pooled-laser-baseline.json" spell85)
foreach(pair IN ITEMS "laser_slot;7" "laser_hitbox_call;4")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell85}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID85 changed pooled-laser source: ${spell85}")
  endif()
endforeach()
foreach(seed IN ITEMS 0 1 65535)
  scene(spell85-portfolio-seed${seed} 4b 85 ${seed} spell-portfolio 4000 complete 0 2792)
  file(READ "${WORK}/spell85-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_rigid_laser_paths rigid_paths)
  if(NOT profile STREQUAL "\"id85-rigid-laser-motion\"" OR NOT rigid_paths GREATER 0)
    message(FATAL_ERROR "ID85 did not exercise its pooled-laser motion model: ${report}")
  endif()
endforeach()
# Preserve the unadapted ID89 failure: its rotating beam is an ECL-owned
# CalcLaserHitbox call rather than a BulletManager laser.
scene(spell89-direct-laser-baseline 4b 89 0 hazard-reactive 1000 collision 2 393)
file(READ "${WORK}/spell89-direct-laser-baseline.json" spell89)
foreach(pair IN ITEMS "laser_slot;-1" "laser_hitbox_call;0")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell89}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID89 direct-laser ${key} changed: ${actual}")
  endif()
endforeach()
run("${EXECUTABLE}" "${WORK}/spell89-direct-laser-diagnostic.json" 2
  --stage 4b --spell-id 89 --difficulty 0 --seed 0 --frames 1000
  --replay "${WORK}/spell89-direct-laser-baseline.actions" --trace "${WORK}/spell89.tsv")
file(READ "${WORK}/spell89-direct-laser-diagnostic.json" spell89_diagnostic)
agree("${spell89}" "${spell89_diagnostic}")
file(STRINGS "${WORK}/spell89.tsv" direct_hitbox
  REGEX "^393.*after.*laser_hitbox.*-1")
if(NOT direct_hitbox)
  message(FATAL_ERROR "ID89 direct ECL hitbox was absent from the diagnostic trace")
endif()
foreach(seed IN ITEMS 0 1 65535)
  scene(spell89-portfolio-seed${seed} 4b 89 ${seed} spell-portfolio 4000 complete 0 3162)
  file(READ "${WORK}/spell89-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_direct_laser_constrained_decisions constrained)
  if(NOT profile STREQUAL "\"id89-direct-ecl-laser\"" OR NOT constrained GREATER 0)
    message(FATAL_ERROR "ID89 did not exercise its ECL candidate constraint: ${report}")
  endif()
endforeach()
# ID93 creates a one-frame-startup pooled laser after the policy decision. By
# the first observed LaserView, input latency makes the measured hit unavoidable.
# Preserve that failure and require a source-decoded, currently due opcode-114
# warning with no unsupported future substituted into the three seeded runs.
scene(spell93-pooled-laser-baseline 4b 93 0 hazard-reactive 2000 collision 2 1539)
file(READ "${WORK}/spell93-pooled-laser-baseline.json" spell93)
foreach(pair IN ITEMS "laser_slot;0" "laser_hitbox_call;0")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell93}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID93 changed imminent pooled-laser source: ${spell93}")
  endif()
endforeach()
foreach(seed IN ITEMS 0 1 65535)
  scene(spell93-portfolio-seed${seed} 4b 93 ${seed} spell-portfolio 5000 complete 0 3392)
  file(READ "${WORK}/spell93-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_imminent_laser_due_spawns due)
  field("${report}" policy_imminent_laser_warnings warnings)
  field("${report}" policy_imminent_laser_unsupported_spawns unsupported)
  field("${report}" policy_imminent_laser_constrained_decisions constrained)
  if(NOT profile STREQUAL "\"id93-imminent-pooled-laser\"" OR
     NOT due STREQUAL "82" OR NOT warnings STREQUAL "82" OR
     NOT unsupported STREQUAL "0" OR NOT constrained GREATER 0)
    message(FATAL_ERROR "ID93 did not exercise its source-owned spawn warning: ${report}")
  endif()
endforeach()
# ID198's fixed-origin beam requires the same observed rotation model as ID85,
# but constant paths oscillate into a later bullet/beam trap. Preserve that
# first failure and require the isolated two-leg proposal set through spell end.
scene(spell198-pooled-laser-baseline extra 198 0 hazard-reactive 1000 collision 2 446 4)
file(READ "${WORK}/spell198-pooled-laser-baseline.json" spell198)
foreach(pair IN ITEMS "laser_slot;0" "laser_hitbox_call;0")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell198}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID198 changed pooled-laser source: ${spell198}")
  endif()
endforeach()
foreach(seed IN ITEMS 0 1 65535)
  scene(spell198-portfolio-seed${seed} extra 198 ${seed} spell-portfolio 6000 complete 0 4292 4)
  file(READ "${WORK}/spell198-portfolio-seed${seed}.json" report)
  field("${report}" policy_profile_last profile)
  field("${report}" policy_first_leg_updates first_leg)
  field("${report}" policy_rigid_laser_paths rigid_paths)
  field("${report}" policy_bullet_projections projections)
  if(NOT profile STREQUAL "\"id198-two-leg-rigid-laser\"" OR
     NOT first_leg STREQUAL "4" OR NOT rigid_paths GREATER 0 OR NOT projections GREATER 0)
    message(FATAL_ERROR "ID198 did not exercise its two-leg cached forecast: ${report}")
  endif()
endforeach()
# ID201's first unadapted collision is a large parent still executing WAIT.
# Preserve that source boundary, then require the isolated adapter to exercise
# both the source-bounded WAIT path and deterministic future opcode-97 shots.
scene(spell201-wait-baseline extra 201 0 hazard-reactive 1000 collision 2 362 4)
file(READ "${WORK}/spell201-wait-baseline.json" spell201)
foreach(pair IN ITEMS "bullet_slot;24" "active_transforms;131072")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell201}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID201 changed delayed-bullet ${key}: ${actual}")
  endif()
endforeach()
scene(spell201-portfolio-seed0 extra 201 0 spell-portfolio 6000 complete 0 4292 4)
file(READ "${WORK}/spell201-portfolio-seed0.json" spell201_portfolio)
foreach(pair IN ITEMS "policy_profile_last;\"id201-wait-and-ecl-shot\""
                      "policy_bullet_horizon;32"
                      "policy_upcoming_bullet_unsupported_spawns;0")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${spell201_portfolio}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "ID201 changed ${key}: ${actual}")
  endif()
endforeach()
foreach(key IN ITEMS policy_wait_linear_checks policy_upcoming_bullet_observed_spawns
                     policy_upcoming_bullet_warnings
                     policy_upcoming_bullet_constrained_decisions)
  field("${spell201_portfolio}" "${key}" actual)
  if(NOT actual GREATER 0)
    message(FATAL_ERROR "ID201 did not exercise ${key}: ${spell201_portfolio}")
  endif()
endforeach()
# Distinct spell profiles guard the measured portfolio boundary. ID195 needs
# vector acceleration; ID199 deliberately retains constant-velocity ranking.
scene(spell193-portfolio extra 193 0 spell-portfolio 5000 complete 0 3692 4)
scene(spell195-portfolio extra 195 0 spell-portfolio 6000 complete 0 4712 4)
scene(spell199-portfolio extra 199 0 spell-portfolio 5000 complete 0 4292 4)
foreach(pair IN ITEMS "spell193-portfolio;source-vector-ranking"
                      "spell195-portfolio;source-vector-ranking"
                      "spell199-portfolio;id199-linear-ranking")
  list(GET pair 0 name)
  list(GET pair 1 expected)
  file(READ "${WORK}/${name}.json" report)
  field("${report}" policy_profile_last actual)
  if(NOT actual STREQUAL "\"${expected}\"")
    message(FATAL_ERROR "${name}: selected ${actual}, expected ${expected}")
  endif()
endforeach()

# Diagnostics must observe the existing failure without changing its trajectory.
set(stage6_tape "${WORK}/stage6b-reactive.actions")
file(READ "${WORK}/stage6b-reactive.json" baseline)
field("${baseline}" trace_digest baseline_digest)
if(NOT baseline_digest STREQUAL "\"4060221407534777929\"")
  message(FATAL_ERROR "The preserved Stage 6b baseline changed")
endif()
run("${EXECUTABLE}" "${WORK}/stage6b-diagnostic.json" 2
  --stage 6b --frames 50000 --replay "${stage6_tape}" --trace "${WORK}/stage6b.tsv")
file(READ "${WORK}/stage6b-diagnostic.json" diagnostic)
agree("${baseline}" "${diagnostic}")
foreach(pair IN ITEMS "bullet_slot;664" "movement_input;133" "sampled_input;4165")
  list(GET pair 0 key)
  list(GET pair 1 expected)
  field("${diagnostic}" "${key}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Unexpected collision ${key}: ${actual}")
  endif()
endforeach()

# Same-update input replacement is too late for movement. One update earlier,
# three leftward directions survive the actual collision boundary.
foreach(frame IN ITEMS 854 853)
  set(directory "${WORK}/probe${frame}")
  execute_process(COMMAND "${PROBE_EXECUTABLE}" --executable "${EXECUTABLE}"
    --dat "${DAT}" --stage 6b --difficulty 0 --seed 0 --actions "${stage6_tape}"
    --frame "${frame}" --through-frame 854 --output-dir "${directory}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Probe ${frame} failed: ${stdout} ${stderr}")
  endif()
  file(READ "${directory}/summary.json" probe)
  list(APPEND probes "${probe}")
  foreach(branch RANGE 0 8)
    file(READ "${directory}/branch${branch}.json" report)
    field("${report}" outcome outcome)
    field("${report}" prefix_frame prefix_frame)
    math(EXPR expected_prefix "${frame} - 1")
    if(NOT prefix_frame STREQUAL "${expected_prefix}")
      message(FATAL_ERROR "Probe verified the wrong prefix boundary")
    endif()
    if((frame EQUAL 854 AND branch EQUAL 3) OR (frame EQUAL 853 AND branch EQUAL 5))
      field("${report}" trace_digest unchanged_digest)
      if(NOT unchanged_digest STREQUAL baseline_digest)
        message(FATAL_ERROR "The unchanged direction did not reproduce the source baseline")
      endif()
    endif()
    if(frame EQUAL 853 AND branch MATCHES "^(0|3|6)$")
      if(NOT outcome STREQUAL "\"frame_limit\"")
        message(FATAL_ERROR "Early leftward intervention no longer avoids the hit")
      endif()
    elseif(NOT outcome STREQUAL "\"collision\"")
      message(FATAL_ERROR "Preserved collision counterfactual changed")
    endif()
    # A second optimization level checks the exact same independent branch tape.
    if(COMPARE_EXECUTABLE)
      run("${COMPARE_EXECUTABLE}" "${directory}/branch${branch}-comparison.json" 2
        --stage 6b --frames 854 --replay "${directory}/branch${branch}.actions"
        --prefix-frame "${expected_prefix}" --allow-unused-actions 1)
      file(READ "${directory}/branch${branch}-comparison.json" comparison)
      agree("${report}" "${comparison}")
    endif()
  endforeach()
endforeach()

file(WRITE "${WORK}/illegal.actions" "32768\n")
run("${EXECUTABLE}" "${WORK}/illegal.json" 1 --replay "${WORK}/illegal.actions")
file(READ "${WORK}/stage1-budget.actions" prefix)
file(WRITE "${WORK}/excess.actions" "${prefix}4\n")
run("${EXECUTABLE}" "${WORK}/excess.json" 1 --frames 10 --replay "${WORK}/excess.actions")
# Explicit diagnostic suffix truncation stays a frame-limit failure and reports
# the unused input. Strict replay above still rejects the same tape by default.
run("${EXECUTABLE}" "${WORK}/bounded-prefix.json" 2 --frames 10
  --replay "${WORK}/excess.actions" --allow-unused-actions 1)
file(READ "${WORK}/bounded-prefix.json" bounded)
field("${bounded}" unused_actions unused)
if(NOT unused STREQUAL "1")
  message(FATAL_ERROR "Unused diagnostic suffix was not recorded")
endif()
execute_process(COMMAND "${PROBE_EXECUTABLE}" --executable "${EXECUTABLE}"
  --dat "${DAT}" --actions "${stage6_tape}" --frame 855 --output-dir "${WORK}/invalid-probe"
  RESULT_VARIABLE invalid_probe OUTPUT_QUIET ERROR_QUIET)
if(NOT invalid_probe STREQUAL "1")
  message(FATAL_ERROR "An out-of-tape intervention was accepted")
endif()
# An engine practice wrapper can choose another raw ID for an invalid stage/ID pair.
run("${EXECUTABLE}" "${WORK}/wrong-checkpoint.json" 1
  --stage 6b --spell-id 178 --strategy reactive --frames 2000)

string(JOIN ",\n" records_json ${records})
string(JOIN ",\n" probes_json ${probes})
set(probe_comparison_checked false)
if(COMPARE_EXECUTABLE)
  set(probe_comparison_checked true)
endif()
cmake_host_system_information(RESULT host_cpu QUERY PROCESSOR_DESCRIPTION)
cmake_host_system_information(RESULT host_platform QUERY OS_PLATFORM)
file(WRITE "${WORK}/summary.json"
  "{\"producer\":\"tests/headless_real_data.cmake + th08_headless + th08_headless_probe\",\"host_processor\":\"${host_cpu}\",\"host_system\":\"${CMAKE_HOST_SYSTEM_NAME}\",\"host_architecture\":\"${host_platform}\",\"runs\":[\n${records_json}\n],\"probes\":[\n${probes_json}\n],\"illegal_input_rejected\":true,\"excess_tape_rejected\":true,\"wrong_checkpoint_rejected\":true,\"invalid_probe_rejected\":true,\"diagnostics_preserve_trajectory\":true,\"probe_comparison_checked\":${probe_comparison_checked}}\n")
