include("${CMAKE_CURRENT_LIST_DIR}/headless_report_checks.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/headless_stage6b_contract.cmake")
file(READ "${ROOT}/reports/native/headless_summary.json" historical)
string(REGEX MATCH "\"case\":\"stage6b-reactive\",\"execution\":(\\{[^}]+\\}\\})" matched "${historical}")
set(original "${CMAKE_MATCH_1}")
if(NOT original)
  message(FATAL_ERROR "Missing preserved historical Stage6b record")
endif()
if(MODE)
  set(changed "${original}")
  if(MODE STREQUAL "rng")
    string(REPLACE "\"rng_seed\":54466" "\"rng_seed\":54467" changed "${changed}")
  elseif(MODE STREQUAL "fractional-rng")
    string(REPLACE "\"rng_seed\":54466" "\"rng_seed\":54466.1" changed "${changed}")
  elseif(MODE STREQUAL "collision")
    string(REPLACE "\"vx\":0.907954931" "\"vx\":0.907954932" changed "${changed}")
  elseif(MODE STREQUAL "dat")
    string(REPLACE "9d7edf43" "0d7edf43" changed "${changed}")
  elseif(MODE STREQUAL "replay")
    string(REPLACE "4060221407534777929" "1" changed "${changed}")
    agree("${original}" "${changed}")
    return()
  endif()
  stage6b_semantic_contract("${changed}" metadata)
  return()
endif()
stage6b_semantic_contract("${original}" metadata)
if(NOT metadata MATCHES "\"historical_digest_match\":true")
  message(FATAL_ERROR "Historical digest provenance was not retained")
endif()
string(REPLACE "4060221407534777929" "1" other_environment "${original}")
stage6b_semantic_contract("${other_environment}" metadata)
if(NOT metadata MATCHES "\"historical_digest_match\":false" OR
   NOT metadata MATCHES "\"numerical_profile_match\":\"unverified\"")
  message(FATAL_ERROR "Unpinned numerical profile was not disclosed")
endif()
foreach(mode IN ITEMS rng fractional-rng collision dat replay)
  execute_process(COMMAND "${CMAKE_COMMAND}" -DROOT=${ROOT} -DMODE=${mode}
    -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
  if(NOT status EQUAL 1)
    message(FATAL_ERROR "Altered ${mode} incorrectly passed its contract")
  endif()
endforeach()
