#include <array>
#include <th08/schema.hpp>

namespace th08::resources {
namespace {
// Payload layouts audited against a45e99f and the actual resource corpus.
// Null layouts remain explicitly unknown; a name is not an execution contract.
constexpr std::array<OpcodeSchema, 185> schemas{{
    {"DEFAULT_NOP_0", ""},
    {"TERMINATE", ""},
    {"SET_SECONDARY_TIME", "i"},
    {"NOP", ""},
    {"JUMP", "ii"},
    {"JUMP_DEC", "iii"},
    {"SET_INT", "ii"},
    {"SET_FLOAT", "ff"},
    {"SET_INT_RANDOM_SIGN", "ii"},
    {"SET_FLOAT_RANDOM_SIGN", "ff"},
    {"INT_ADD_ASSIGN", "ii"},
    {"INT_SUBTRACT_ASSIGN", "ii"},
    {"INT_MULTIPLY_ASSIGN", "ii"},
    {"INT_DIVIDE_ASSIGN", "ii"},
    {"INT_MODULO_ASSIGN", "ii"},
    {"FLOAT_ADD_ASSIGN", "ff"},
    {"FLOAT_SUBTRACT_ASSIGN", "ff"},
    {"FLOAT_MULTIPLY_ASSIGN", "ff"},
    {"FLOAT_DIVIDE_ASSIGN", "ff"},
    {"FLOAT_MODULO_ASSIGN", "ff"},
    {"INT_ADD", "iii"},
    {"INT_SUBTRACT", "iii"},
    {"INT_MULTIPLY", "iii"},
    {"INT_DIVIDE", "iii"},
    {"INT_MODULO", "iii"},
    {"FLOAT_ADD", "fff"},
    {"FLOAT_SUBTRACT", "fff"},
    {"FLOAT_MULTIPLY", "fff"},
    {"FLOAT_DIVIDE", "fff"},
    {"FLOAT_MODULO", "fff"},
    {"INT_INCREMENT", "i"},
    {"INT_DECREMENT", "i"},
    {"FLOAT_SINE", "ff"},
    {"FLOAT_COSINE", "ff"},
    {"POINT_ANGLE", "fffff"},
    {"INTERPOLATE_VALUE", nullptr},
    {"INSTALL_INTERPOLATION", "fiiiffff"},
    {"NORMALIZE_ANGLE", "f"},
    {"POLAR_TO_CARTESIAN", "ffff"},
    {"POINT_DISTANCE", "fffff"},
    {"JUMP_IF_INT_EQUAL", "iiii"},
    {"JUMP_IF_FLOAT_EQUAL", "ffii"},
    {"JUMP_IF_INT_NOT_EQUAL", "iiii"},
    {"JUMP_IF_FLOAT_NOT_EQUAL", "ffii"},
    {"JUMP_IF_INT_LESS", "iiii"},
    {"JUMP_IF_FLOAT_LESS", "ffii"},
    {"JUMP_IF_INT_LESS_EQUAL", "iiii"},
    {"JUMP_IF_FLOAT_LESS_EQUAL", "ffii"},
    {"JUMP_IF_INT_GREATER", "iiii"},
    {"JUMP_IF_FLOAT_GREATER", "ffii"},
    {"JUMP_IF_INT_GREATER_EQUAL", "iiii"},
    {"JUMP_IF_FLOAT_GREATER_EQUAL", "ffii"},
    {"CALL", "i"},
    {"RETURN", ""},
    {"SET_MAIN_ANM", "i"},
    {"SET_PRIMARY_ANM_SEQUENCE", "i"},
    {"SET_PRIMARY_ANM_SCRIPTS", "iiiiii"},
    {"SET_EXTRA_ANM_SCRIPT", "ii"},
    {"SET_MAIN_ANM_ALTERNATE", "i"},
    {"SET_PRIMARY_ANM_SEQUENCE_ALTERNATE", "i"},
    {"SET_PRIMARY_ANM_SCRIPTS_ALTERNATE", "iiiiii"},
    {"SET_EXTRA_ANM_SCRIPT_ALTERNATE", "ii"},
    {"PLAY_SPECIAL_ANM", ""},
    {"SET_POSITION", "ff"},
    {"MOVE_TO", "iiff"},
    {"SET_DIRECTION_AND_SPEED", "ff"},
    {"MOVE_IN_DIRECTION", "iiff"},
    {"MOVE_RANDOM_IN_BOUNDS", "iif"},
    {"SET_AIMED_DIRECTION_AND_SPEED", "ff"},
    {"MOVE_IN_AIMED_DIRECTION", "iiff"},
    {"SET_ANGULAR_VELOCITY", "f"},
    {"SET_ACCELERATION", "f"},
    {"ORBIT_AROUND_POINT", "iffffff"},
    {"ORBIT_AROUND_CURRENT_POSITION", "ifff"},
    {"SET_ORBIT_VELOCITIES", "iff"},
    {"SET_MOVEMENT_BOUNDS", "ffff"},
    {"DISABLE_MOVEMENT_BOUNDS", ""},
    {"SET_HITBOX", "ff"},
    {"SET_SECONDARY_HITBOX", "ff"},
    {"SET_INTERACTION_FLAGS", "i"},
    {"DISABLE_INTERACTION_FLAGS", "i"},
    {"ENABLE_INTERACTION_FLAGS", "i"},
    {"SET_MINIMUM_PLAYER_DISTANCE", "f"},
    {"SET_FORM_EFFECT_ENABLED", "i"},
    {"NOP_84", nullptr},
    {"NOP_85", nullptr},
    {"SET_REMOTE_INT", nullptr},
    {"SET_REMOTE_FLOAT", "ffi"},
    {"CALL_REMOTE", "ii"},
    {"SCHEDULE_REMOTE_SUBROUTINE", "ii"},
    {"SPAWN_FAMILIAR_AT_POSITION", "iffiii"},
    {"SPAWN_FAMILIAR_AT_OFFSET", "iffiii"},
    {"SPAWN_FAMILIAR_INHERITING_POSITION", "iffiii"},
    {"SPAWN_ENEMY_AT_POSITION", "ifffiii"},
    {"SPAWN_ENEMY_RELATIVE", "ifffiii"},
    {"KILL_ALL_NON_BOSS_ENEMIES", ""},
    {"SHOOT_FAN_AIMED", "hhiiffffI"},
    {"SHOOT_FAN", "hhiiffffI"},
    {"SHOOT_CIRCLE_AIMED", "hhiiffffI"},
    {"SHOOT_CIRCLE", "hhiiffffI"},
    {"SHOOT_OFFSET_CIRCLE_AIMED", "hhiiffffI"},
    {"SHOOT_OFFSET_CIRCLE", "hhiiffffI"},
    {"SHOOT_RANDOM_ANGLE", "hhiiffffI"},
    {"SHOOT_RANDOM_SPEED", "hhiiffffI"},
    {"SHOOT_RANDOM", "hhiiffffI"},
    {"SET_SHOOT_INTERVAL", "i"},
    {"SET_SHOOT_INTERVAL_DELAYED", "i"},
    {"ENABLE_DEFERRED_SHOOTING", ""},
    {"DISABLE_DEFERRED_SHOOTING", ""},
    {"SHOOT_NOW", ""},
    {"SET_SHOOT_OFFSET", "ff"},
    {"SET_BULLET_TRANSFORM", "iiiiiff"},
    {"CLEAR_BULLETS_FOR_TRANSITION", ""},
    {"SET_BULLET_SOUNDS", "ii"},
    {"CREATE_LASER", "hhffffffiiiiiI"},
    {"CREATE_LASER_AIMED", "hhffffffiiiiiI"},
    {"SELECT_LASER_SLOT", "i"},
    {"ROTATE_LASER", "if"},
    {"AIM_LASER_AT_PLAYER", "if"},
    {"SET_LASER_POSITION", "ifff"},
    {"TEST_LASER_ACTIVE", "i"},
    {"CANCEL_LASER", "i"},
    {"START_SPELL", nullptr},
    {"END_SPELL", ""},
    {"PLAY_POSITIONED_SOUND", "i"},
    {"CALL_SUBROUTINE_SLOT", "i"},
    {"SET_SUBROUTINE_SLOT", "ii"},
    {"SET_BOSS", "i"},
    {"ATTACH_SPELL_EFFECT", "iffff"},
    {"SET_DEATH_MODE", "i"},
    {"SET_DEATH_CALLBACK", "i"},
    {"SET_LIFE", "i"},
    {"SET_BOSS_TIMER", "i"},
    {"SET_LIFE_CALLBACK", "iii"},
    {"SET_TIMER_CALLBACK", "ii"},
    {"SET_CHILD_ECL", "ii"},
    {"CALL_EX_INSTRUCTION", "ii"},
    {"SET_REPEATING_EX_INSTRUCTION", "ii"},
    {"SET_DEATH_ANM_SCRIPTS", "i"},
    {"SPAWN_EFFECT", "iii"},
    {"SPAWN_EFFECT_WITH_VELOCITY", "iiifff"},
    {"SPAWN_ITEM", "i"},
    {"DROP_POWER_OR_POINT_ITEMS", "i"},
    {"SET_ITEM_DROP_TYPE", "i"},
    {"SET_ITEM_DROP_COUNTS", "ii"},
    {"SET_ANM_ROTATION_ENABLED", "i"},
    {"ADD_TIME", "i"},
    {"SET_BACKGROUND_SCRIPT_LABEL", "i"},
    {"SET_BOSS_LIFE_MARKER_COUNT", "i"},
    {"INTERRUPT_MAIN_ANM", "i"},
    {"INTERRUPT_SECONDARY_ANM", "ii"},
    {"SET_CALL_STACK_DISABLED", "i"},
    {"SET_BULLET_RANK_INFLUENCE", "ffiiii"},
    {"RESET_BOSS_TIMER_CALLBACK", ""},
    {"CLEAR_LASER_SLOTS", ""},
    {"SET_TIMEOUT_SPELL", "i"},
    {"SET_SPECIAL_INTERACTION", "i"},
    {"SET_TRAIL", "iiii"},
    {"SET_BOSS_GAUGE_SLOT", "iiii"},
    {"SET_DRAW_GROUP", "i"},
    {"SET_DAMAGE_REDUCTION_TIMER", "i"},
    {"REMOVE_BULLETS_IN_RADIUS", "f"},
    {"REMOVE_ALL_BULLETS", ""},
    {"SET_MANAGER_PROTOCOL_VALUE", "i"},
    {"SET_SPELL_EFFECT_TRACKING_DISABLED", "i"},
    {"SET_MAIN_ANM_ROTATION", "f"},
    {"POLAR_TO_CARTESIAN_ALT", "ffff"},
    {"SET_LASER_ANGLE", "if"},
    {"DROP_POINT_ITEMS", "i"},
    {"RANDOM_HORIZONTAL_ANGLE", "fff"},
    {"SET_LASER_START_CAP_HIDDEN", "ii"},
    {"SET_LASER_START_LENGTH", "if"},
    {"SET_LASER_OFFSETS", "iff"},
    {"SET_TIMER_PAUSED", "i"},
    {"REPLACE_ALIGNMENT_EFFECT", "i"},
    {"SET_TIMELINE_SPAWNS_SUPPRESSED", "i"},
    {"PREPARE_STAGE_TIME_STOP", "i"},
    {"SET_PHASE_STARTING_LIFE", "i"},
    {"MOVE_RANDOM_BIASED", "iif"},
    {"START_STAGE_BACKGROUND_SEQUENCE", ""},
    {"HIDE_CLOCK_TIME", ""},
    {"INCREMENT_CLOCK_TIME", ""},
    {"SET_EXTRA_ANM_FIXED_OFFSET", "i"},
    {"SET_NO_DAMAGE_DURING_STOP", "i"},
    {"SET_BONUS_UPDATES_DISABLED", "i"},
}};
} // namespace
const OpcodeSchema &opcode_schema(unsigned opcode) {
    if (opcode >= schemas.size())
        throw std::out_of_range("ECL opcode outside schema table");
    return schemas[opcode];
}
PayloadStatus check_payload(unsigned opcode, std::size_t bytes) {
    if (opcode == 3)
        return bytes == 0 || bytes == 4 ? PayloadStatus::known : PayloadStatus::mismatch;
    if (opcode == 122)
        // Header fields, two 48-byte encoded labels, two 64-byte comment lines.
        return bytes == 232 ? PayloadStatus::known : PayloadStatus::mismatch;
    const auto *fields = opcode_schema(opcode).fields;
    if (!fields)
        return PayloadStatus::unknown;
    std::size_t expected = 0;
    for (; *fields; ++fields)
        expected += *fields == 'h' ? 2 : 4;
    return expected == bytes ? PayloadStatus::known : PayloadStatus::mismatch;
}
} // namespace th08::resources
